package com.freelanceapp.myRequestPkg.MyRequestOptionsPkg.myRequestPublishedPkg.Fragment;

import androidx.fragment.app.Fragment;

import com.freelanceapp.myRequestPkg.MyRequestOptionsPkg.myRequestPublishedPkg.Adapter.MyRequestPublishedDateAdapter;
import com.freelanceapp.myRequestPkg.MyRequestOptionsPkg.myRequestPublishedPkg.Adapter.MyRequestPublishedNoteAdapter;

public class MyRequestPublishedDateFragment extends Fragment implements MyRequestPublishedDateAdapter.MyRequestPublishedDateAppOnClickListener{


}
